language: node_js
sudo: false
node_js:
  - "node"
services:
  - mongodb
env:
  - CXX=g++-4.8 SECRET=test PORT=3000 MONGO_URI=mongodb://localhost/lacoloc
script:
  - yarn test:check-coverage
after_script:
  - yarn report-coverage
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
